name: "FRP HA"
description: "Klient FRP dla Home Assistant"
version: "1.1.1"
slug: "frp_ha"
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: "auto"
map:
  - type: share
    read_only: false
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
schema:
  server: str
  token: str
  subdomain: str
  proxy_name: str
  protocol:
    type: select
    options:
      - http
      - https
  port:
    type: int
    minimum: 1
    maximum: 65535
  useCompression: bool
  useEncryption: bool