name: "FRP HA"
description: "Klient FRP dla Home Assistant"
version: "1.1.5"
slug: "frp_ha_addon"
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: "auto"
map:
  - type: share
    read_only: false
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
options:
  port: 8123
  subdomain: "match(^[a-zA-Z]*-frp$)"
  useCompression: true
  useEncryption: true
schema:
  server: str
  token: str
  proxy_name: str
  protocol: "list(http|https)"
  subdomain: str
  port: int
  useCompression: bool
  useEncryption: bool
