serverAddr = "__arg_server_address__"
serverPort = 7000

auth.method = "token"
auth.token = "__arg_auth_token__"

[[proxies]]
name = "__arg_proxy_name__"
type = "__arg_protocol__"
localIP = "127.0.0.1"
localPort = "__arg_local_port__"
subdomain = "__arg_subdomain__"
transport.useEncryption = "__arg_use_encryption__"
transport.useCompression = "__arg_use_compression__"
